server:
  servlet:
    context-path: /bicibff
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

logging:
  level:
    root: DEBUG

# ================
# ZUUL Api Gateway
# ===============
zuul:
  routes:
    user:
      url: ${USER_HOST}/api/user
      path: /user/**

    profile:
      url: ${USER_HOST}/api/profile
      path: /profile/**

    tour:
      url: ${USER_HOST}/api/tour
      path: /tour/**

    bicycle:
      url: ${BICI_HOST}/api/bicycle
      path: /bicycle/**

    rent:
      url: ${BICI_HOST}/api/rent
      path: /rent/**

    company:
      url: ${COMPANY_HOST}/api/company
      path: /company/**

    place:
      url: ${PLACE_HOST}/api/v1/place
      path: /place/**

  sensitive-headers: Cookie,Set-Cookie

# ================
# CORS
# ===============

api:
  origins:
    front:
      server: '*'
